### ISSUE TITLE
Cumulative todo

### ISSUE THREAD

**Issue by paolodina** [paolodina/sveltekit-edgedb#1]
Unordered todo list.

- [x] leverage edgedb e2e type safety using the typescript query builder
- [x] fix pnpm check
- [x] add homepage placeholder and separete `/blog` route
- [x] alias
  - `$blog`
  - `$dbschema`
- [x] add `LICENSE`
- [x] update `README`
- [ ] fixtures (test data)
- [ ] dedicated route matcher
- [ ] endpoints
  - [ ] full text search
  - [ ] rss endpoint
  - [ ] sitemap
- [ ] advanced search with filters
- [ ] results pagination
- [x] move edgedb client out from `page.server`
- [x] conf linter/formatter
- [ ] dynamic component sidebar
- [ ] crud
  - [x] list
  - [ ] create
  - [ ] update
  - [ ] delete
- [ ] user
  - [ ] login
  - [ ] signup
- [ ] additional blog post fields + migration
- [ ] tags implementation
